version: '3.9'
services:
  backend:
    container_name: langdex-backend
    image: dev-langdex
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    networks:
      - langdex
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGODB_URL: mongodb://127.0.0.1:27017/db/Langdex
    healthcheck:
      test: ['CMD', '/usr/bin/wget', '--tries=1', '--spider', 'localhost:3000']
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  mongo:
    container_name: langdex-db
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    networks:
      - langdex
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      timeout: 10s
      interval: 10s
      retries: 10
      start_period: 30s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: langdex123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: langdex123
      ME_CONFIG_MONGODB_SERVER: langdex-db
    depends_on: 
      mongo:
        condition: service_healthy
    networks:
      - langdex

networks:
  langdex:
